import React from 'react'
import Link from 'next/link'
import styles from './page.module.css'



export const metadata = {
  title: 'Clinica Dental',
  description: 'Generated by create next app',
}

export default function notFound() {
  return (
    <>
      <div className={styles.container}>
        <h2 className={styles.title}>Página no encontrada</h2>
        <Link className={styles.volver} href="/">Volver</Link>
      </div>
    </>
  )
}
